<div id="wechat_subscriber" style="display: block; padding: 10px 0; margin: 20px auto; width: 100%; text-align: center">
    <div style="font-weight:bold;text-align:left;font-size:16px">{{ theme.wechat_subscriber.description }}</div>
   <br />
    <img id="wechat_subscriber_qcode" src="{{ theme.wechat_subscriber.qcode }}" alt="{{ theme.author }} wechat" align="middle" style="width: 600px; max-width: 100%;"/>
 <br />
</div>
